export const app = document.getElementById('app')
export const githubUsernameInput = document.getElementById('search-input')
export const userFavoriteButton = document.getElementById('favorite-btn')
export const table = document.querySelector('main table tbody')
export const noFavoritesMessage = document.querySelector('.no-favorites')